name: 'Mark PDF'
description: 'Add a short text and sha to a PDF'
author: 'Oliver Butterley'
inputs:
  in_file: 
    description: 'input pdf filename'
    required: true
    default: 'main.pdf' 
  out_file: 
    description: 'output pdf filename'
    required: true
    default: 'marked-main.pdf' 
  text: 
    description: 'Text to be added to pdf'
    required: true
    default: ''
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: book-open
  color: blue